---
# Role metadata
galaxy_info:
  author: cuiv
  description: Common configuration for all homelab hosts and containers
  license: MIT
  min_ansible_version: "2.9"

  platforms:
    - name: Debian
      versions:
        - bullseye
        - bookworm

dependencies: []
