---
# Handlers for common role

- name: Restart sshd
  ansible.builtin.service:
    name: "{{ 'ssh' if ansible_facts['os_family'] == 'Debian' else 'sshd' }}"
    state: restarted

- name: Restart dhcpcd
  ansible.builtin.service:
    name: dhcpcd
    state: restarted
