$ANSIBLE_VAULT;1.1;AES256
62626538356566323736393234353937616334336139313764306662316264313931376536326366
3839356131636232313561353531653961323638336232330a336437666665633862653038643061
31323263623630663261613434303630666564623834616665363864666266396630613963356662
3833333131626234310a626539306534646339383736623666623962663265303438343735316638
64653237643633666266396639373030626138373537353166623562646539303438666138656164
30383266653533623430386565316361373761356133356536613838633231653866346364366635
34663331633938393439646166626661346439383163613138633361653564393631623564336531
65356164346233343266356663653732383863323738313061613361393762313464303362303863
31303735323830383234356364323666653036313061323039353566376265633433333964626461
30316135356566303736386566653331376637616261333666333637616234356130373638313437
63353163386536306634326263643766313434666633636161373333666532636235313531623463
63623066356332336133316432306563643666633662636338316162353965643736333039316232
66366133376633396563383038636665336335333335303531666333303763663430313031393833
35313432393036373136343131643333623961356264636332333861383435386236376633306234
61393062303330373332326639323962363832636661353638613632373964373432663033313335
38653463343437353761
