$ANSIBLE_VAULT;1.1;AES256
32356264393964343937313738636566646261613662653962653336343064633937666134373031
6438666433386437616134333064663337333833666233300a613134323430316361383134636232
36376165643338386539643764353137663966373166623264376234353935303038653831643137
6532663837616333340a626231366231616135326666303865616331653863303438386666613066
34323862303438653939383762363834633861313731313862393234316530323663393361316432
65646132386265663333623866363637313866383161336235653334323232633539613166393437
62623031636432623030616561356664353666366235616466373964653130643532366233316161
32646431386630653138393763343537393132656639373262393530653264316531303939376430
34323036643863343937623265333830613238346532373232333764326232643538363532623066
33363238303236346136356265383535356633613161346462373163376663646562393065643035
35336264646231363836656337306234383031613766313937323231333537366539653932366434
62383332356362636231303033353731386263663434316664316662383163653630333061326230
32613035313236623339373233373833343932323437346335383063303430343038323031306663
64643364303765306161633762393735346465333533643634303433613161636639346438386138
31396565623565653439636462376563313333353432316161303962333261313938643133303865
63383134303561343832383765343163336439303338633932383266663236336137653931653034
39313132393930636135646439313131333431646534333736366636383432343634343635633331
38616634316239626635306534353765646465313532386466353837353633306536396664613937
62313739323030656661343361333437643633333434346564353461383234303237646466636236
38303430323664626239383364383937386630633965333736376236333037326366353663376638
35643332306238633538353663396139323364613735633961336165393933323634653233643237
36336262373539653433346537643938303663316261643436613265633364636536653531363165
66363831343232363466363835646439663030373930323364613430646463396461333830336339
64613133646537386333343035393933346332323264306233366534323562323234306663323064
38646135616635316433316337306433613334666436383564333334333164626535333465356561
30653239626331616630623331663932383736643762316636316535656465633539613437623033
36613333653864363438393930393933663161316334373366373931613630346239336538356663
37636362643063356333
