---
# Handlers for mealie role

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  become: true

- name: Restart mealie
  ansible.builtin.systemd:
    name: mealie
    state: restarted
  become: true
