---
# Optical drive passthrough handlers

- name: Restart container
  ansible.builtin.shell: "pct stop {{ container_id }} && sleep 2 && pct start {{ container_id }}"
  delegate_to: homelab
  when: container_id is defined
