---
# Handlers for proxmox_storage role

- name: Mount all disks
  ansible.builtin.command: mount -a
  listen: Mount all disks

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Snapraid config changed
  ansible.builtin.debug:
    msg: "SnapRAID configuration has been updated"
